[35mDEBUG   [0m asyncio:proactor_events.py:631 Using proactor: IocpProactor
[32mINFO    [0m root:Calculation_test.py:151 --- Starting calculation Test for S8 | Credit Card | 1001-5000 | 1200 ---
[32mINFO    [0m root:client_helper.py:8 Filling client code: TM001
[32mINFO    [0m root:client_helper.py:12 Selecting environment: STAGING
[32mINFO    [0m root:client_helper.py:16 Clicking Show Detail button
[33mWARNING [0m root:client_helper.py:21 Payer Name not visible. Retrying Show Detail...
[31m[1mERROR   [0m root:Calculation_test.py:214 Exception occurred during Cancel Transaction Test for TM001: Locator.select_option: Timeout 30000ms exceeded.
Call log:
waiting for locator("select[name='environment']")
Traceback (most recent call last):
  File "C:\Users\Bhargava\Desktop\QA project\sabpaisa_pg_qa_automation\testCases\Calculation_test.py", line 173, in test_calculation_amount
    fill_and_verify_client_details(self.logger, client, client_details, excel_client_code, excel_environment)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhargava\Desktop\QA project\sabpaisa_pg_qa_automation\.venv\Lib\site-packages\allure_commons\_allure.py", line 202, in impl
    return func(*a, **kw)
  File "C:\Users\Bhargava\Desktop\QA project\sabpaisa_pg_qa_automation\utilites\client_helper.py", line 23, in fill_and_verify_client_details
    client.select("_environment", environment)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhargava\Desktop\QA project\sabpaisa_pg_qa_automation\pageObjects\base_page.py", line 32, in select
    self.page.locator(locator).select_option(option)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "C:\Users\Bhargava\Desktop\QA project\sabpaisa_pg_qa_automation\.venv\Lib\site-packages\playwright\sync_api\_generated.py", line 17293, in select_option
    self._sync(
    ~~~~~~~~~~^
        self._impl_obj.select_option(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
        )
        ^
    )
    ^
  File "C:\Users\Bhargava\Desktop\QA project\sabpaisa_pg_qa_automation\.venv\Lib\site-packages\playwright\_impl\_sync_base.py", line 115, in _sync
    return task.result()
           ~~~~~~~~~~~^^
  File "C:\Users\Bhargava\Desktop\QA project\sabpaisa_pg_qa_automation\.venv\Lib\site-packages\playwright\_impl\_locator.py", line 557, in select_option
    return await self._frame.select_option(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\Bhargava\Desktop\QA project\sabpaisa_pg_qa_automation\.venv\Lib\site-packages\playwright\_impl\_frame.py", line 678, in select_option
    return await self._channel.send("selectOption", params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bhargava\Desktop\QA project\sabpaisa_pg_qa_automation\.venv\Lib\site-packages\playwright\_impl\_connection.py", line 59, in send
    return await self._connection.wrap_api_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        lambda: self.inner_send(method, params, False)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Bhargava\Desktop\QA project\sabpaisa_pg_qa_automation\.venv\Lib\site-packages\playwright\_impl\_connection.py", line 520, in wrap_api_call
    raise rewrite_error(error, f"{parsed_st['apiName']}: {error}") from None
playwright._impl._errors.TimeoutError: Locator.select_option: Timeout 30000ms exceeded.
Call log:
waiting for locator("select[name='environment']")